export const BASIS_POINTS_SCALE = 10_000n;

export const HEALTH_FACTOR_SCALE = BASIS_POINTS_SCALE;
export const HEALTH_FACTOR_SCORE_MAX = 10;
export const HEALTH_FACTOR_SAFE_THRESHOLD = 15_000n;
export const HEALTH_FACTOR_AT_RISK_THRESHOLD = 10_500n;

export const LTV_LIMIT_PERCENT = 80;
export const LTV_LIMIT_BPS = 8_000n;
